# change localhost with respective containers

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8222
spring:
  application:
    name: gatewayService
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:


#          filters:
#            - AuthenticationFilter

        - id: authenticationService
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

        - id: binService
          uri: http://localhost:8082
          predicates:
            - Path=/bins/**

        - id: truckService
          uri: http://localhost:8083
          predicates:
            - Path=/api/trucks/**

        - id: issueService
          uri: http://localhost:8084
          predicates:
            - Path=/issues/**

        - id: routeService
          uri: http://localhost:8085
          predicates:
            - Path=/api/routes/**





